version: '3.4'

services:
  cefacapi:
    image: ${DOCKER_REGISTRY-}cefacapi
    build:
      context: .
      dockerfile: CefacAPI/Dockerfile
    ports:
    - "5000:80"
    links:
    - "redis_compose"
    depends_on:
    - "redis_compose"

  redis_compose:
    image: redis
    restart: always
    hostname: redis
    ports:
    - "6379:6379"
